services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    environment:
      SA_PASSWORD: "TwojeHaslo123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_sportcenter_data:/var/opt/mssql
    networks:
      - backend-net

  migrator:
    build:
      context: .
      target: migrator
    container_name: db_migrator
    depends_on:
      mssql:
        condition: service_started
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=SportCenter;User=sa;Password=TwojeHaslo123!;TrustServerCertificate=true
    networks:
      - backend-net
    command: >
        /bin/sh -c "
        echo 'Czekam na gotowość bazy danych...' &&
        until dotnet ef database update --project /src/SportCenterApi.csproj --startup-project /src/SportCenterApi.csproj; do
            echo 'Baza jeszcze niedostępna. Czekam 5s...' &&
            sleep 5;
        done &&
        echo 'Migracja zakończona sukcesem!'"

  backend:
    build:
      context: .
      target: final
    container_name: backend_app
    ports:
      - "5000:80"
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=SportCenter;User=sa;Password=TwojeHaslo123!;TrustServerCertificate=true
      - ASPNETCORE_ENVIRONMENT=Production
      - ENV ASPNETCORE_URLS=http://+:80
      - ENV ASPNETCORE_HTTP_PORT=80
    networks:
      - backend-net

volumes:
  mssql_sportcenter_data:
    driver: local

networks:
  backend-net:
    driver: bridge